export const MODULES = [
  "Dashboard",
  "Servicios",
  "Categorías",
  "Citas",
  "Horarios",
  "Empleados",
  "Clientes",
  "Cotizaciones",
  "Ventas",
  "Usuarios",
  "Roles",
  "Reportes",
];

export const ACTIONS = [
  "Ver",
  "Crear",
  "Editar",
  "Eliminar",
  "Exportar",
  "Gestionar",
];

export const MODULE_COLORS: Record<string, string> = {
  Dashboard: "bg-blue-100 text-blue-700",
  Servicios: "bg-purple-100 text-purple-700",
  Categorías: "bg-pink-100 text-pink-700",
  Citas: "bg-green-100 text-green-700",
  Horarios: "bg-cyan-100 text-cyan-700",
  Empleados: "bg-teal-100 text-teal-700",
  Clientes: "bg-indigo-100 text-indigo-700",
  Cotizaciones: "bg-amber-100 text-amber-700",
  Ventas: "bg-emerald-100 text-emerald-700",
  Usuarios: "bg-violet-100 text-violet-700",
  Roles: "bg-fuchsia-100 text-fuchsia-700",
  Reportes: "bg-orange-100 text-orange-700",
};

export const ACTION_COLORS: Record<string, string> = {
  Ver: "bg-blue-50 text-blue-600",
  Crear: "bg-green-50 text-green-600",
  Editar: "bg-amber-50 text-amber-600",
  Eliminar: "bg-red-50 text-red-600",
  Exportar: "bg-purple-50 text-purple-600",
  Gestionar: "bg-indigo-50 text-indigo-600",
};

export const INITIAL_PERMISSIONS = [
  {
    id: 1,
    name: "Ver Dashboard",
    description: "Permite acceder y visualizar el panel principal del sistema",
    module: "Dashboard",
    action: "Ver",
    isActive: true,
    createdAt: "2024-01-10",
    rolesCount: 4,
  },
  {
    id: 2,
    name: "Crear Servicios",
    description: "Permite crear nuevos servicios en el catálogo",
    module: "Servicios",
    action: "Crear",
    isActive: true,
    createdAt: "2024-01-12",
    rolesCount: 2,
  },
  {
    id: 3,
    name: "Editar Servicios",
    description: "Permite modificar servicios existentes",
    module: "Servicios",
    action: "Editar",
    isActive: true,
    createdAt: "2024-01-12",
    rolesCount: 2,
  },
  {
    id: 4,
    name: "Ver Citas",
    description: "Permite visualizar las citas programadas",
    module: "Citas",
    action: "Ver",
    isActive: true,
    createdAt: "2024-01-15",
    rolesCount: 5,
  },
  {
    id: 5,
    name: "Crear Citas",
    description: "Permite programar nuevas citas para clientes",
    module: "Citas",
    action: "Crear",
    isActive: true,
    createdAt: "2024-01-15",
    rolesCount: 4,
  },
  {
    id: 6,
    name: "Eliminar Clientes",
    description: "Permite eliminar registros de clientes del sistema",
    module: "Clientes",
    action: "Eliminar",
    isActive: false,
    createdAt: "2024-02-01",
    rolesCount: 1,
  },
  {
    id: 7,
    name: "Gestionar Usuarios",
    description: "Permite crear, editar y eliminar usuarios del sistema",
    module: "Usuarios",
    action: "Gestionar",
    isActive: true,
    createdAt: "2024-01-10",
    rolesCount: 1,
  },
  {
    id: 8,
    name: "Exportar Reportes",
    description: "Permite exportar reportes en diferentes formatos",
    module: "Reportes",
    action: "Exportar",
    isActive: true,
    createdAt: "2024-02-10",
    rolesCount: 2,
  },
];